language: node_js
node_js:
  - 12

script:
  - npm run coverage
  - npm run build:docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TSTRUCT_PAGES_TOKEN
  local_dir: docs
  keep_history: true
  on:
    branch: master

# by default tavis runs npm install and npm test